image: node:latest

cache:
  paths:
  - node_modules/

gitlab_commit_sort:
  before_script:
    - git checkout master
    - git config --global user.email "github@softvenue.net"
    - git config --global user.name "SoftVenue CI"
  script:
    - npm i
    - npm run test
  after_script:
    - git add i18n.json
    - git add i18n.yml
    - git commit -m "SoftVenue CI update [ci skip]"
    - git remote add gitlab https://${GH_TOKEN}@github.com/softvenue/i18n.git
    - git push gitlab master
